#
##
### Written by the CAT team
##
#
heat_template_version: 2013-05-23

description: High Aviability Toolbox stack for Cloudwatt


parameters:
  keypair_name:
    description: Keypair to inject in instance
    label: SSH Keypair
    type: string

  os_username:
    description: OpenStack Username
    label: OpenStack Username
    type: string

  os_password:
    description: OpenStack Password
    label: OpenStack Password
    type: string

  os_tenant:
    description: OpenStack Tenant Name
    label: OpenStack Tenant Name
    type: string

  os_auth:
    description: OpenStack Auth URL
    default: https://identity.fr1.cloudwatt.com/v2.0
    label: OpenStack Auth URL
    type: string

  domain:
    description: Wildcarded domain, ex example.com must have a *.example.com DNS entry
    default: toolbox
    label: Cloud DNS
    type: string

  flavor_name:
    default: n1.cw.standard-4
    description: Flavor to use for the deployed instance
    type: string
    label: Instance Type (Flavor)
    constraints:
      - allowed_values:
          - n1.cw.standard-4
          - n2.cw.standard-4
          - n2.cw.standard-8
          - n2.cw.standard-16


  volume_size:
    default: 10
    label: Backup Volume Size
    description: Size of Volume for Toolbox Storage (Gigabytes)
    type: number
    constraints:
      - range: { min: 10, max: 10000 }
        description: Volume must be at least 10 gigabytes

  volume_type:
    default: standard
    label: Backup Volume Type
    description: Performance flavor of the linked Volume for DevKit Storage
    type: string
    constraints:
      - allowed_values:
          - standard
          - performant

  node_count:
    default: 1
    label: Node Count
    description: Additional node counts
    type: number
    constraints:
      - range: { min: 0, max: 30 }

resources:
  network:
    type: OS::Neutron::Net

  subnet:
    type: OS::Neutron::Subnet
    properties:
      network_id: { get_resource: network }
      ip_version: 4
      cidr: 10.0.0.0/16
      allocation_pools:
        - { start: 10.0.1.100, end: 10.0.1.199 }

  router:
    type: OS::Neutron::Router
    properties:
      admin_state_up: true
      external_gateway_info:
        enable_snat: true
        network: "public"

  toolbox_interface:
    type: OS::Neutron::RouterInterface
    properties:
      router_id: { get_resource: router }
      subnet_id: { get_resource: subnet }

  security_group:
    type: OS::Neutron::SecurityGroup
    properties:
      rules:
        - { direction: ingress }
        - { direction: egress }

  masters:
    type: OS::Heat::ResourceGroup
    properties:
      count: 3
      resource_def:
        type: https://storage.fr1.cloudwatt.com/v1/AUTH_772be1ffb32e42a28ac8e0205c0b0b90/toolbox/ha/kube-master.heat.yaml
        properties:
          nodename: master-%index%
          nodeip: 10.0.1.25%index%
          domain: { get_param: domain }
          subnet: { get_resource: subnet }
          security_group: { get_resource: security_group }
          network: { get_resource: network }
          keypair_name: { get_param: keypair_name }
          flavor_name: { get_param: flavor_name }
          volume_size: { get_param: volume_size }
          volume_type: { get_param: volume_type }
          os_username: { get_param: os_username }
          os_password: { get_param: os_password }
          os_tenant: { get_param: os_tenant }
          os_auth: { get_param: os_auth }

  masterpool_etcd:
    type: OS::Neutron::Pool
    properties:
      name: masterpool_etcd
      protocol: TCP
      lb_method: ROUND_ROBIN
      subnet_id: { get_resource: subnet }
      vip:
        protocol_port: 2380

  masterpool_kube:
    type: OS::Neutron::Pool
    properties:
      name: masterpool_kube
      protocol: TCP
      lb_method: ROUND_ROBIN
      subnet_id: { get_resource: subnet }
      vip:
        protocol_port: 443

  masterpool_nfs:
    type: OS::Neutron::Pool
    properties:
      name: masterpool_nfs
      protocol: TCP
      lb_method: ROUND_ROBIN
      subnet_id: { get_resource: subnet }
      vip:
        protocol_port: 2049

  masterlb_etcd:
    type: OS::Neutron::LoadBalancer
    properties:
      members: { get_attr: [masters, refs, master] }
      pool_id: { get_resource: masterpool_etcd }
      protocol_port: 2380

  masterlb_kube:
    type: OS::Neutron::LoadBalancer
    properties:
      members: { get_attr: [masters, refs, master] }
      pool_id: { get_resource: masterpool_kube }
      protocol_port: 443

  masterlb_nfs:
    type: OS::Neutron::LoadBalancer
    properties:
      members: { get_attr: [masters, refs, master] }
      pool_id: { get_resource: masterpool_nfs }
      protocol_port: 2049

  nodes:
    type: OS::Heat::ResourceGroup
    properties:
      count: { get_param: node_count }
      resource_def:
        type: https://storage.fr1.cloudwatt.com/v1/AUTH_772be1ffb32e42a28ac8e0205c0b0b90/toolbox/ha/kube-node.heat.yaml
        properties:
          domain: { get_param: domain }
          master_etcd: { get_attr: [masterpool_etcd, vip, address] }
          master_kube: { get_attr: [masterpool_kube, vip, address] }
          master_nfs: { get_attr: [masterpool_nfs, vip, address] }
          security_group: { get_resource: security_group }
          network: { get_resource: network }
          nodename: node-%index%
          keypair_name: { get_param: keypair_name }
          flavor_name: { get_param: flavor_name }

