---
#
##
### Written by the CAT (Cloudwatt Automation Team)
##
#
- hosts: '{{openstack_id}}'
  become: yes

  vars:
    package: aptly


  tasks:

  - name : install httplib2
    pip: name=httplib2
         state=present


  - name: config repo
    lineinfile:
      dest=/etc/apt/sources.list
      line="deb http://{{ toolbox_adress }}:8080/ {{ ansible_distribution_release }} main"

  - uri:
       url: http://{{ toolbox_adress }}:4001/v2/keys/servers/{{ openstack_id }}/apps/aptly
       method: PUT
       HEADER_Content-Type: "application/x-www-form-urlencoded"
       status_code: 200,201
       body_format: raw
       body: "value={{ package }}"
