---
#
##
### Written by the CAT (Cloudwatt Automation Team)
##
#
- hosts: '{{openstack_id}}'
  become: yes

  vars:
    package: duplicity

  tasks:
    - name:  packages installed
      package:
          name=duplicity
          state=present

    - uri:
         url: http://{{ toolbox_adress }}:4001/v2/keys/servers/{{ openstack_id }}/apps/ntpserver
         method: PUT
         HEADER_Content-Type: "application/x-www-form-urlencoded"
         body_format: raw
         body: "value={{ package }}"
