---
#
##
### Written by the CAT (Cloudwatt Automation Team)
##
#
- hosts: '{{openstack_id}}'
  user: cloud
  become: yes

  vars:
    package: duplicity

  tasks:

    - name : install httplib2
      pip: name=httplib2
           state=present


    - name:  packages installed
      package:
          name=duplicity
          state=present

    - uri:
         url: http://{{ toolbox_adress }}:2379/v2/keys/servers/{{ openstack_id }}/apps/duplicity
         method: PUT
         HEADER_Content-Type: "application/x-www-form-urlencoded"
         status_code: 200,201
         body_format: raw
         body: "value={{ package }}"
