---
#
##
### Written by the CAT (Cloudwatt Automation Team)
##
#
- hosts: servers
  user: cloud
  become: yes

  vars:
    package: graylog

  tasks:

    - name: Create file
      template:
        dest=/etc/rsyslog.d/90-graylog2.conf
        src=graylog-file/90-graylog2.j2


    - name: restart rsyslog
      service:
        name=rsyslog
        state=restarted


    - uri:
        url: http://{{ toolbox_address }}:2379/v2/keys/servers/{{ openstack_id }}/apps/graylog
        method: PUT
        HEADER_Content-Type: "application/x-www-form-urlencoded"
        status_code: 200,201
        body_format: raw
        body: "value={{ package }}"
