---
#
##
### Written by the CAT (Cloudwatt Automation Team)
##
#
- hosts: '{{openstack_id}}'
  user: cloud
  become: yes

  vars:
    package: ntp

  tasks:
     - name : install NTP
       apt: pkg=ntp
           state=present

     - name : install httplib2
       pip: name=httplib2
           state=present

     - name: config ntp client
       lineinfile:
        dest=/etc/ntp.conf
        line="server {{toolbox_adress}}"

     - uri:
         url: http://{{ toolbox_adress }}:4001/v2/keys/servers/{{ openstack_id }}/apps/ntpserver
         method: PUT
         HEADER_Content-Type: "application/x-www-form-urlencoded"
         status_code: 200,201
         body_format: raw
         body: "value={{ package }}"
