---
#
##
### Written by the CAT (Cloudwatt Automation Team)
##
#
- hosts: '{{openstack_id}}'
  user: cloud
  become: yes

  vars:
    package: zabbix
    server_ip: server_ip
    toolbox_adress: toolbox_adress
    openstack_id: openstack_id
  tasks:
    - apt: update_cache=true upgrade=full

    - name: install packages
      apt: pkg={{ item }} state=present
      with_items:
        - zabbix-agent
        - ntp
      notify: restart ntp

    - name: get zabbix_server IP
      lineinfile:
        name=/etc/zabbix/zabbix_agentd.conf
        regexp=".*Server=.*"
        line="Server={{ toolbox_adress }}"

    - name: zabbix slave hostname
      lineinfile:
        name=/etc/zabbix/zabbix_agentd.conf
        regexp="^Hostname="
        line="Hostname={{ ansible_hostname }}"
      notify: restart zabbix

    - name : install httplib2
      pip: name=httplib2
            state=present

    - uri:
        url: http://{{ toolbox_adress }}:2379/v2/keys/servers/{{ openstack_id }}/apps/zabbix
        method: PUT
        HEADER_Content-Type: "application/x-www-form-urlencoded"
        status_code: 200,201
        body_format: raw
        body: "value={{ package }}"




  handlers:
    - name: restart ntp
      service:
        name=ntp
        state=restarted
        enabled=yes

    - name: restart zabbix
      service:
        name=zabbix-agent
        state=restarted
        enabled=yes





