---
#
##
### Written by the CAT (Cloudwatt Automation Team)
##
#
- hosts: servers
  user: cloud
  become: yes

  vars:
    package: aptly


  tasks:

  - name : install httplib2
    pip: name=httplib2
         state=present


  - name: config repo
    lineinfile:
      dest=/etc/apt/sources.list
      line="deb http://{{ toolbox_address }}:8080/ {{ ansible_distribution_release }} main"
    when: (ansible_distribution == "Ubuntu") or (ansible_distribution == "Debian")

  - name: add repository
    yum:
      name=http://{{ toolbox_address }}:8080/ {{ ansible_distribution_release }} main
      state=present
    when: ansible_distribution == "CentOS"

  - uri:
       url: http://{{ toolbox_address }}:2379/v2/keys/servers/{{ openstack_id }}/apps/aptly
       method: PUT
       HEADER_Content-Type: "application/x-www-form-urlencoded"
       status_code: 200,201
       body_format: raw
       body: "value={{ package }}"
