---
#
##
### Written by the CAT (Cloudwatt Automation Team)
##
#
- hosts: servers
  user: cloud
  become: yes

  vars:
    package: aptly
    local_home: "{{ lookup('env') }}"


  tasks:

  - apt: update_cache=true upgrade=full
    when: (ansible_distribution == "Ubuntu") or (ansible_distribution == "Debian")

  - name : install httplib2
    pip: name=httplib2
         state=present


  - name: config repo
    lineinfile:
      dest=/etc/apt/sources.list
      line="deb http://{{ local_home.SERVICE_HOST }}:{{ local_home.SERVICE_PORT }}/ {{ ansible_distribution_release }} main"
    when: (ansible_distribution == "Ubuntu") or (ansible_distribution == "Debian")

  - name: add repository
    yum:
      name=http://aptly.{{ local_home.SERVICE_HOST }}/ {{ ansible_distribution_release }} main
      state=present
    when: ansible_distribution == "CentOS"


