---
#
##
### Written by the CAT (Cloudwatt Automation Team)
##
#
- hosts: servers
  become: yes

  vars:
    package: aptly
    service: "{{ lookup('env', 'SERVICE_HOST') }}:{{ lookup('env', 'SERVICE_PORT') }}"


  tasks:

  - apt: update_cache=true upgrade=full
    when: (ansible_distribution == "Ubuntu") or (ansible_distribution == "Debian")

  - name : install httplib2
    pip: name=httplib2
         state=present


  - name: config repo
    lineinfile:
      dest=/etc/apt/sources.list
      line="deb http://{{ service }}/ubuntu {{ ansible_distribution_release }} main"
    when: (ansible_distribution == "Ubuntu")

  - name: config repo
    lineinfile:
      dest=/etc/apt/sources.list
      line="deb http://{{ service }}/debian {{ ansible_distribution_release }} main"
    when: (ansible_distribution == "Debian")

  - name: add repository
    yum:
      name=http://{{ service }}/ {{ ansible_distribution_release }} main
      state=present
    when: ansible_distribution == "CentOS"

