---
#
##
### Written by the CAT (Cloudwatt Automation Team)
##
#
- hosts: servers
  user: cloud
  become: yes

  vars:
    package: clamav
    service: "{{ lookup('env', 'SERVICE_HOST') }}:{{ lookup('env', 'SERVICE_PORT') }}"

  tasks:

    - apt: update_cache=true upgrade=full
      when: (ansible_distribution == "Ubuntu") or (ansible_distribution == "Debian")

    - name: Add repository
      yum:
        name=http://download.fedoraproject.org/pub/epel/6/x86_64/epel-release-6-8.noarch.rpm
        state=present
      when:  ansible_distribution == "CentOS" and ansible_distribution_version.split(".")[0] == "6"

    - name: Add repository
      yum:
        name=https://dl.fedoraproject.org/pub/epel/epel-release-latest-7.noarch.rpm
        state=present
      when:  ansible_distribution == "CentOS" and ansible_distribution_version.split(".")[0] == "7"


    - name: install packages Ubuntu
      package: name={{ item }} state=present
      with_items:
        - curl
        - clamav
        - clamav-freshclam
        - clamav-data
      when: (ansible_distribution == "Ubuntu") or (ansible_distribution == "Debian")

    - name: install packages Centos
      package: name={{ item }} state=present
      with_items:
        - epel-release
        - curl
        - clamav-server
        - clamav-data
        - clamav-update
        - clamav-filesystem
        - clamav
        - clamav-scanner-systemd
        - clamav-devel
        - clamav-lib
        - clamav-server-systemd
      when:  ansible_distribution == "CentOS" and ansible_distribution_version.split(".")[0] == "7"

    - name: install packages Centos
      package: name={{ item }} state=present
      with_items:
        - curl
        - clamav-server
        - clamav-data
        - clamav-update
        - clamav-filesystem
        - clamav
        - clamav-devel
        - clamav-lib
      when:  ansible_distribution == "CentOS" and ansible_distribution_version.split(".")[0] == "6"

    - name: set selinux permissions
      selinux: policy=antivirus_can_scan_system state=permissive
      when: ansible_distribution == "CentOS"

    - name: change config freshclam Ubuntu/Debian
      template:
        dest=/etc/clamav/freshclam.conf
        src=clamav-file-ubuntu/clamav.j2
      when: (ansible_distribution == "Ubuntu") or (ansible_distribution == "Debian")

    - name: Copy config clamd
      copy:
        src=clamav-file-centos/clamd.conf
        dest=/etc/clamd.d/clamd.conf
      when: ansible_distribution == "CentOS"

    - name: Copy config freshclam
      template:
        src=clamav-file-centos/freshclam.j2
        dest=/etc/freshclam.conf
      when: ansible_distribution == "CentOS"

    - name: Copy config freshclam service
      copy:
        src=clamav-file-centos/clam-freshclam.service
        dest=/usr/lib/systemd/system/clam-freshclam.service
      when: ansible_distribution == "CentOS" and ansible_distribution_version.split(".")[0] == "7"

    - name: enable service clamav
      shell:
        sudo systemctl enable clam-freshclam.service; \
        sudo systemctl start clam-freshclam.service
      when: ansible_distribution == "CentOS" and ansible_distribution_version.split(".")[0] == "7"

    - name: enable freshclam
      lineinfile:
        name=/etc/sysconfig/freshclam
        regexp="^FRESHCLAM_DELAY=disabled"
        line="#FRESHCLAM_DELAY=disabled-warn"
      when: ansible_distribution == "CentOS" and ansible_distribution_version.split(".")[0] == "7"

    - name: clamav update script
      template:
        src=clamav-update.j2
        dest=/usr/bin/clamav-update.sh
        mode=755

    - cron: name="fetch clamav updates" minute="0" hour="1" job=/usr/bin/clamav-update.sh

    - name: restart clamav
      service:
        name=clamav-freshclam
        state=restarted
        enabled=yes
      when: (ansible_distribution == "Ubuntu") or (ansible_distribution == "Debian")
