---
#
##
### Written by the CAT (Cloudwatt Automation Team)
##
#
- hosts: servers
  become: yes

  vars:
    package: duplicity

  tasks:

    - apt: update_cache=true upgrade=full
      when: (ansible_distribution == "Ubuntu") or (ansible_distribution == "Debian")

    - name : install httplib2
      pip: name=httplib2
           state=present


    - name:  packages installed
      package:
          name=duplicity
          state=present


