---
#
##
### Written by the CAT (Cloudwatt Automation Team)
##
#
- hosts: servers
  user: cloud
  become: yes

  vars:
    package: duplicity

  tasks:

    - apt: update_cache=true upgrade=full
      when: (ansible_distribution == "Ubuntu") or (ansible_distribution == "Debian")

    - name : install httplib2
      pip: name=httplib2
           state=present


    - name:  packages installed
      package:
          name=duplicity
          state=present

    - uri:
         url: http://{{ toolbox_address }}:2379/v2/keys/servers/{{ openstack_id }}/apps/duplicity
         method: PUT
         HEADER_Content-Type: "application/x-www-form-urlencoded"
         status_code: 200,201
         body_format: raw
         body: "value={{ package }}"
