---
#
##
### Written by the CAT (Cloudwatt Automation Team)
##
#
- hosts: servers
  user: cloud
  become: yes

  vars:
    package: nexus
    service: "{{ lookup('env', 'SERVICE_HOST') }}:{{ lookup('env', 'SERVICE_PORT') }}"

  tasks:

  - name: add yum repo
    template:
      src=nexus-file-centos/nexus.repo.j2
      dest=/etc/yum.repos.d/nexus.repo
    when : ansible_distribution == "CentOS"
