---
#
##
### Written by the CAT (Cloudwatt Automation Team)
##
#
- hosts: servers
  user: cloud
  become: yes

  vars:
    package: nexus
    local_home: "{{ lookup('env') }}"

  tasks:

  - name: add yum repo
    template:
      src=nexus-file-centos/nexus.repo.j2
      dest=/etc/yum.repos.d/nexus.repo
    when : ansible_distribution == "CentOS"

  - name : install httplib2
    pip:
      name=httplib2
      state=present

