---
#
##
### Written by the CAT (Cloudwatt Automation Team)
##
#
- hosts: servers
  user: cloud
  become: yes

  vars:
    package: nexus


  tasks:

  - name: add yum repo
    template:
      src=nexus-file-centos/nexus.repo.j2
      dest=/etc/yum.repos.d/nexus.repo
    when : ansible_distribution == "CentOS"

  - name : install httplib2
    pip:
      name=httplib2
      state=present

  - uri:
     url: http://{{ ansible_env.SERVICE_HOST }}:2379/v2/keys/servers/{{ openstack_id }}/apps/nexus
     method: PUT
     HEADER_Content-Type: "application/x-www-form-urlencoded"
     status_code: 200,201
     body_format: raw
     body: "value={{ package }}"