---
#
##
### Written by the CAT (Cloudwatt Automation Team)
##
#
- hosts: servers
  user: cloud
  become: yes

  vars:
    package: nexus
    server_ip: server_ip
    toolbox_address: toolbox_address
    openstack_id: openstack_id

  tasks:

  - name: add yum repo
    shell:
      cp http://{{ toolbox_address}}.repo /etc/yum.repos.d/
    when : ansible_distribution == "CentOS"

  - uri:
     url: http://{{ toolbox_address }}:2379/v2/keys/servers/{{ openstack_id }}/apps/nexus
     method: PUT
     HEADER_Content-Type: "application/x-www-form-urlencoded"
     status_code: 200,201
     body_format: raw
     body: "value={{ package }}"





