---
#
##
### Written by the CAT (Cloudwatt Automation Team)
##
#
- hosts: servers
  become: yes

  vars:
    package: ntp
    service: "{{ lookup('env', 'SERVICE_HOST') }}"
  tasks:

    - apt: update_cache=true upgrade=full
      when: (ansible_distribution == "Ubuntu") or (ansible_distribution == "Debian")

    - name: install NTP
      package: name=ntp
               state=present

    - name: install pip
      package: name=python-pip
               state=present

    - name: install httplib2
      pip: name=httplib2
           state=present

    - name: config ntp client
      lineinfile: dest=/etc/ntp.conf
                  line="server {{ service }}"


    - name: restart ntp
      when: (ansible_distribution == "Ubuntu") or (ansible_distribution == "Debian")
      service: name=ntp
               state=restarted
               enabled=yes

    - name: restart ntpd
      when: (ansible_distribution == "CentOS")
      service: name=ntpd
               state=restarted
               enabled=yes
