---
#
##
### Written by the CAT (Cloudwatt Automation Team)
##
#

- hosts: servers
  user: cloud
  become: yes

  vars:
    package: skydns

  tasks:

    - apt: update_cache=true upgrade=full
      when: (ansible_distribution == "Ubuntu") or (ansible_distribution == "Debian")

    - name: add toolbox adress in resolv.conf
      lineinfile:
        dest=/etc/resolv.conf
        line="nameserver {{toolbox_address}}"

    - name : install httplib2
      pip: name=httplib2
           state=present

    - uri:
        url: http://{{ toolbox_address }}:2379/v2/keys/servers/{{ openstack_id }}/apps/skydns
        method: PUT
        HEADER_Content-Type: "application/x-www-form-urlencoded"
        status_code: 200,201
        body_format: raw
        body: "value={{ package }}"