---
#
##
### Written by the CAT (Cloudwatt Automation Team)
##
#

- hosts: servers
  become: yes

  vars:
    package: skydns

  tasks:

    - apt: update_cache=true upgrade=full
      when: (ansible_distribution == "Ubuntu") or (ansible_distribution == "Debian")

    - name: add toolbox adress in resolv.conf
      lineinfile:
        dest=/etc/resolv.conf
        line="nameserver {{toolbox_address}}"

