---
#
##
### Written by the CAT (Cloudwatt Automation Team)
##
#
- hosts: servers
  user: cloud
  become: yes

  vars:
    package: zabbix
    service: "{{ lookup('env', 'SERVICE_ZABBIX-ACTIVE_HOST') }}:{{ lookup('env', 'SERVICE_ZABBIX-ACTIVE_PORT') }}"

  tasks:

    - apt: update_cache=true upgrade=full
      when: (ansible_distribution == "Ubuntu") or (ansible_distribution == "Debian")

    - name: Add repository
      yum:
        name=http://repo.zabbix.com/zabbix/2.2/rhel/7/x86_64/zabbix-release-2.2-1.el7.noarch.rpm
        state=present
      when: ansible_distribution == "CentOS"

    - name: install packages
      package: name={{ item }} state=present
      with_items:
        - zabbix-agent


    - name: set ServerActive IP
      lineinfile:
        name=/etc/zabbix/zabbix_agentd.conf
        regexp=".*ServerActive=.*"
        line="ServerActive= {{ service }}"
      notify: restart zabbix

    - name: zabbix slave hostname
      lineinfile:
        name=/etc/zabbix/zabbix_agentd.conf
        regexp="^Hostname="
        line="Hostname={{ ansible_hostname }}"
      notify: restart zabbix

    - name : install httplib2
      pip: name=httplib2
            state=present

  handlers:
    - name: restart zabbix
      service:
        name=zabbix-agent
        state=restarted
        enabled=yes





