---
#
##
### Written by the CAT (Cloudwatt Automation Team)
##
#
- hosts: servers
  user: cloud
  become: yes

  vars:
    package: zabbix
    service_web: "{{ lookup('env', 'SERVICE_WEB_HOST') }}:{{ lookup('env', 'SERVICE_WEB_PORT') }}"
    service: "{{ lookup('env', 'SERVICE_ACTIVE_HOST') }}:{{ lookup('env', 'SERVICE_ACTIVE_PORT') }}"
    service_username: "{{ lookup('env', 'ZS_DBUser') }}"
    service_password: "{{ lookup('env', 'ZS_DBPassword') }}"

  tasks:

    - apt: update_cache=true upgrade=full
      when: (ansible_distribution == "Ubuntu") or (ansible_distribution == "Debian")

    - name: Add repository
      yum:
        name=http://repo.zabbix.com/zabbix/2.2/rhel/7/x86_64/zabbix-release-2.2-1.el7.noarch.rpm
        state=present
      when: ansible_distribution == "CentOS"

    - name: install packages
      package: name={{ item }} state=present
      with_items:
        - zabbix-agent

    - name: set ServerActive IP
      lineinfile:
        name=/etc/zabbix/zabbix_agentd.conf
        regexp=".*ServerActive=.*"
        line="ServerActive={{ service }}"
      notify: restart zabbix

    - name: set Server IP
      lineinfile:
        name=/etc/zabbix/zabbix_agentd.conf
        regexp=".*Server=.*"
        line="Server={{ toolbox_address }}"
      notify: restart zabbix

    - name: set Source IP
      lineinfile:
        name=/etc/zabbix/zabbix_agentd.conf
        regexp=".*SourceIP=.*"
        line="SourceIP={{ server_ip }}"
      notify: restart zabbix

    - name: zabbix slave hostname
      lineinfile:
        name=/etc/zabbix/zabbix_agentd.conf
        regexp="^Hostname="
        line="Hostname={{ ansible_hostname }}"
      notify: restart zabbix

    - name : install zabbix-api
      pip: name=zabbix-api
           state=present

    - name: register zabbix agent
      local_action:
          module: zabbix_host
          server_url: "http://{{ service_web }}"
          login_user: "{{ service_username }}"
          login_password: "{{ service_password }}"
          host_name: "{{ ansible_hostname }}"
          host_groups:
            - Linux servers
          status: enabled
          state: present
          inventory_mode: automatic
          interfaces:
            - type: 1
              main: 1
              useip: 1
              ip: "{{ server_ip }}"
              dns: "{{ ansible_hostname }}"
              port: 10050

  handlers:
    - name: restart zabbix
      service:
        name=zabbix-agent
        state=restarted
        enabled=yes





