---
#
##
### Written by the CAT (Cloudwatt Automation Team)
##
#
- hosts: servers
  user: cloud
  become: yes

  vars:
    package: aptly


  tasks:

  - name: unconfig repo
    lineinfile:
      dest=/etc/apt/sources.list
      line="#deb http://{{ toolbox_address }}:8080/ {{ ansible_distribution_release }} main"

      - name: rm repository
      yum:
        name=http://repo.zabbix.com/zabbix/2.2/rhel/7/x86_64/zabbix-release-2.2-1.el7.noarch.rpm
        state=absent
      when: ansible_distribution == "CentOS"

  - uri:
       url: http://{{ toolbox_address }}:2379/v2/keys/servers/{{ openstack_id }}/apps/aptly
       method: DELETE
       status_code: 200,201

