---
#
##
### Written by the CAT (Cloudwatt Automation Team)
##
#
- hosts: servers
  user: cloud
  become: yes

  vars:
    package: aptly


  tasks:

  - name : uninstall httplib2
    pip: name=httplib2
         state=absent


  - name: unconfig repo
    lineinfile:
      dest=/etc/apt/sources.list
      line="#deb http://{{ toolbox_address }}:8080/ {{ ansible_distribution_release }} main"

  - uri:
       url: http://{{ toolbox_address }}:2379/v2/keys/servers/{{ openstack_id }}/apps/aptly
       method: DELETE
       status_code: 200,201

